# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 11:17
from __future__ import unicode_literals

import Tableau.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tableau',
            fields=[
                ('Nom', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('Longueur', models.CharField(default='', max_length=3)),
                ('Largueur', models.CharField(default='', max_length=3)),
                ('Image', models.ImageField(blank=True, max_length=255, null=True, upload_to=Tableau.models.path_and_rename)),
                ('Realisateur', models.CharField(choices=[('Morgane Carluer', 'Morgane Carluer'), ('Christine Carluer', 'Christine Carluer')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nature', models.CharField(choices=[('Aquarelle', 'Aquarelle'), ('Craie', 'Craie'), ('Crayon de couleur', 'Crayon de couleur'), ('Encaustique', 'Encaustique'), ('Encre', 'Encre'), ('Gouache', 'Gouache'), ('Pastel secs et Crayon pastel', 'Pastel secs et Crayon pastel'), ('Pastels gras', 'Pastels gras'), ('Peinture acrylique', 'Peinture acrylique'), ("Peinture \xe0 l'huile", "Peinture \xe0 l'huile"), ('Huile solide', 'Huile solide'), ('Pigments', 'Pigments'), ('Sanguine', 'Sanguine'), ('Feutre', 'Feutre'), ('Tempera', 'Tempera'), ('Crayon graphite', 'Crayon graphite'), ('Encre de Chine', 'Encre de Chine'), ('Fusain', 'Fusain'), ('Mine de plomb', 'Mine de plomb'), ('Pierre noire', 'Pierre noire'), ("Pointe d'argent", "Pointe d'argent")], max_length=30, unique=True)),
                ('Description', models.CharField(default='', max_length=500)),
            ],
            options={
                'ordering': ('Nature',),
            },
        ),
        migrations.AddField(
            model_name='tableau',
            name='Nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tableau.Technique'),
        ),
    ]
