# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Tableau', '0002_tableau_realname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='RealName',
            field=models.UUIDField(default=uuid.UUID('27429bfa-87c2-4ffb-8d0f-706fab98317b'), editable=False, primary_key=True),
        ),
    ]
