# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Tableau', '0003_auto_20180813_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='RealName',
            field=models.UUIDField(default=uuid.UUID('0e05f054-74f2-44ad-9fda-4aff6def66f9'), editable=False, primary_key=True),
        ),
    ]
