# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Tableau', '0004_auto_20180813_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='Nom',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='tableau',
            name='RealName',
            field=models.UUIDField(default=uuid.UUID('304df191-1473-41b5-b711-9b4208868c16'), editable=False, primary_key=True, serialize=False),
        ),
    ]
