# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Tableau', '0005_auto_20180813_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='RealName',
            field=models.UUIDField(default=uuid.UUID('690b3ddc-79c4-4883-be7b-48c23f8e311b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
