# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Tableau', '0006_auto_20180813_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='RealName',
            field=models.UUIDField(default=uuid.UUID('81a3547a-1718-41d2-9bd8-b584a456c72e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
